spring:
  application:
    name: hemorede
  datasource:
    url: jdbc:h2:mem:hemorede;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

hemorede:
  doacao:
    intervalo-minimo-dias-homem: 60
    intervalo-minimo-dias-mulher: 90
  estoque:
    limite-minimo-padrao: 5
