name: CI/CD - Rota Vital

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Compilar projeto
        working-directory: ./rotavital
        run: mvn package -DskipTests

      - name: Executar testes
        working-directory: ./rotavital
        run: mvn test